# Default values for hpcc-efs.
common:
  mountPrefix: "/var/lib/HPCCSystems"
  efsID: fs-05015fb8f507adc57

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  category: dali
  apID: fsap-027ef09b0fcf1c007
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  category: dll
  rwmany: true
  apID: fsap-048075b84b7792e43
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  category: sasha
  apID: fsap-0fcd1ddbbfb15b7d6
- name: data
  subPath: hpcc-data
  size: 3Gi
  category: data # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
  apID: fsap-05974076a216acd14
- name: mydropzone
  subPath: dropzone
  size: 1Gi
  rwmany: true
  category: lz
  apID: fsap-0803903767a6a8094